import mongoose from "mongoose";
import { ST } from "next/dist/shared/lib/utils";

const salesChannelSchema = new mongoose.Schema({
  nzDropshipping: Boolean,
  nzDropshippingAutoCalculate: Boolean,
  nzDropshippingDropdown: String,
  Emailplatformatrackingfile: Boolean,
  ImportFromRTS: String,
  company: String,
  website: String,
  address1: String,
  address2: String,
  firstName: String,
  lastName: String,
  suburbState: String,
  postcode: String,
  email: String,
  phone: String,
  abn: String,
  emailPlatforminvoice: Boolean,
  salesChannelID: String,
  salesChannelName: String,
  salesChannelType: String,
  accountmanagar: String,
  invoice: String,
  tracking: String,
  cancleorder: String,
  startOnCampaign: Boolean,
  dateFrom: String,
  dateTo: String,
  discountPercentage: String,
  campaignNote: String,
  salesChannelCode: String,
  orderNumberPrefix: String,
  descriptionChannel: Boolean,
  sellingChannel: Boolean,
  commissionPercentage: String,
  dropshippingValue: String,
  imageOutputPath: String,
  orderTemplate1: String,
  orderTemplate2: String,
  orderTemplate3: String,
  trackingFileTemplate: String,
  invoiceTemplate: String,
  invoiceOrPO: String,
  invoiceFolder: String,
  "1POINV": Boolean,
  CustomerinvoicelncGST: Boolean,
  missinginvoice: Boolean,
  Emailinvoicerequired: Boolean,
  paymentrequired: Boolean,
  payementterm: String,
  bankReferenceName: String,
  QuickBooksOrderID: String,
  removedtext: String,
  paymentNote: String,
  Currency: String,
  pricingRules: String,
  offSellingPrice: String,
  offSellingPricecheckbox: Boolean,
  plusShipping: Boolean,
  calculateNZPricecheckbox: Boolean,
  calculateNZPrice: String,
  calculateRetailPricecheckbox: Boolean,
  calculateRetailPrice: String,
  calculateGSTcheckbox: Boolean,
  calculateGST: String,
  roundingLowcheckbox: Boolean,
  roundingLow: String,
  roundingHighcheckbox: Boolean,
  roundingHigh: String,
  versioncheckbox:Boolean,
}, { timestamps: true });

export default mongoose.models.SalesChannel || mongoose.model("SalesChannel", salesChannelSchema);
